### ISSUE TITLE
Consider to add IcedCoffee rather than normal Coffeescript?

### ISSUE THREAD

**Issue by PhilAndrew** [softprops/coffeescripted-sbt#11]
As here: http://maxtaco.github.com/coffee-script/

Any chance to add this? Thanks!

**Comment by softprops** [comment]
I saw that go by my radar the other day. If it has a standalone compiler like coffeescript I was thinking about adding a new coffee setting, `iced` which when true, would use that compiler otherwise use the default coffeescript compiler.

**Comment by softprops** [comment]
Looks like it [does](https://github.com/maxtaco/coffee-script/blob/iced/extras/coffee-script-iced.js). I'll have a look tonight, there was also another nice patch someone submitted which should make coffee compilation faster by sharing one compiler instance per sbt session. Both will this and that would probably go in the same release. Good stuff

**Comment by softprops** [comment]
Looks very nice and was trival to add support for. See the [iced](https://github.com/softprops/coffeescripted-sbt/tree/iced) branch. I'll do a new release [1.2.2](https://github.com/softprops/coffeescripted-sbt/blob/iced/notes/0.2.2.markdown) tomorrow evening which includes the other coffee compiler optimization. Thanks for taking the interest!

**Comment by PhilAndrew** [comment]
Hi there Doug, thanks, that's useful!

**Comment by softprops** [comment]
The maintainer seems to be doing releases daily t o fix bugs, meaning that it may not be stable yet. I'm going to wait a few days to see if it does calm down.

**Comment by softprops** [comment]
incorporated in http://implicit.ly/coffeescripted-sbt-022
