### ISSUE TITLE
support for sbt 0.13

### ISSUE THREAD

**Issue by shiphrah** [softprops/coffeescripted-sbt#20]
support for sbt 0.13 would be great :-)

**Comment by softprops** [comment]
You should find 0.2.3 under http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/me.lessis/coffeescripted-sbt/scala_2.10/. Is it not resolving for you?

**Comment by shiphrah** [comment]
sorry, my stupid mistake!

**Comment by softprops** [comment]
no worries. let me know if you find anything else!
