### ISSUE TITLE
CoffeeScript version update?

### ISSUE THREAD

**Issue by sroebuck** [softprops/coffeescripted-sbt#7]
This plugin is great, but it would be nice to have a CoffeeScript compiler update and handy if the notes confirmed which version of CoffeeScript was being used for the compile - I think it's currently v 1.1.1.

There have now been three more releases with some valuable fixes and changes: 1.1.2, 1.1.3 and 1.2.0: http://jashkenas.github.com/coffee-script/#changelog

**Comment by softprops** [comment]
sweet. I that should be simple to change. Ill look into it soon

**Comment by softprops** [comment]
fixed with 61324183dad2df2c789f6faf50fb59f0af944352 ran into some "fun" issues along the way https://github.com/jashkenas/coffee-script/issues/2046
