### ISSUE TITLE
Backporting to sbt 0.7.4

### ISSUE THREAD

**Issue by basetta** [softprops/coffeescripted-sbt#8]
Hi, 

I am asking nicely :) , is there any possibility for a backporting to sbt 0.7.4 ? 

Thanks

**Comment by softprops** [comment]
To support versions before the major 0.10.\* shift, that would require a non-trival amount of work. Fortunately, the guy behind the old coffeescript plugin for sbt 0.7 series seems to still be actively maintaining it, https://github.com/rubbish/coffee-script-sbt-plugin. For older versions of sbt, I recommend using his plugin.

**Comment by epmartini** [comment]
Thanks ! :)
