### ISSUE TITLE
How to add to Build.scala?

### ISSUE THREAD

**Issue by PhilAndrew** [softprops/coffeescripted-sbt#9]
Hi,

You said how to add it to build.sbt, but I have a Build.scala

How can I add it to Build.scala?

Thanks, Philip

**Comment by melezov** [comment]
Hi, here's an example for "full configuration" build:
https://raw.github.com/melezov/gruj/master/project/GrujBuild.scala

**Comment by softprops** [comment]
It looks like you figured it out. Are you still having problems getting it to work. The configuration shouldn't really differ between build.sbt and the scala build definition, aside from not having the `seq(settings...)` function. Let me know if something is not working and I'll have a look.

**Comment by softprops** [comment]
Whoops, I didn't see these posts were from two different people. @philip142au does @melezov's example help? If so, let me know so I can close the this issue. Thanks.

**Comment by PhilAndrew** [comment]
Yes it helped thanks! Also I posted on stackoverflow http://stackoverflow.com/questions/8940411/for-sbt-simple-build-tool-how-to-do-the-same-in-build-scala-as-in-build-sbt
